package com.obinstodo.todolist.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.time.LocalDate;

// Getters, setters, constructors are automatically generated by Lombok annotations
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Accessors(chain = true)
public class Task {
    private int taskId;
    private String title;
    private String description;
    private LocalDate dueDate;
    private boolean completed;


}

