package com.obinstodo.todolist.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.Date;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Task {
    private int taskId;
    private String title;
    private String description;
    private LocalDate dueDate;
    private boolean completed;

    // Getters, setters, constructors are automatically generated by Lombok annotations
}

