apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: europe-west2-docker.pkg.dev/plucky-day-387611/docker-images/todolist:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: LoadBalancer
  selector:
    app: todolist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
