name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.6

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and test
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t todolist:1.0 .

      - name: Log in to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: <your-project-id>
          service_account_key: ${{ secrets.GCR_KEY }}

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Push Docker image to Container Registry
        run: docker push todolist:1.0

      - name: Set up Kubernetes
        uses: google/kubernetes-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml