name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Eclipse Temurin JDK 17
      - uses: actions/setup-java@v2.5.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
  
